[project]
authors = ["yl <2201441955@qq.com>"]
channels = ["conda-forge", "https://conda.modular.com/max", "https://repo.prefix.dev/mojo-community"]
description = "furnace"
name = "furnace"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
test = "mojo test"

[dependencies]
max = "*"
python = "*"
fastapi = ">=0.115.2,<0.116"
uvicorn = ">=0.32.0,<0.33"
orjson = ">=3.10.7,<4"
sortedcontainers = ">=2.4.0,<3"
multidict = ">=6.1.0,<7"
yarl = ">=1.15.5,<2"
small_time = ">=0.1.6,<0.2"
